data: ../../data/processed/shared/dataset.yaml

epochs: 100
batch: 16
imgsz: 640

optimizer: auto

mosaic: 0.0
mixup: 0.0
copy_paste: 0.0

seed: 42

cos_lr: false
hsv_h: 0
degrees: 0
flipud: 0
perspective: 0
